version: '2'

services:
  phonebook-mysql:
    container_name: phonebook-mysql
    build:
      context: .
      dockerfile: Dockerfile-mysql
    restart: always

  phonebook-app:
    container_name: phonebook-app
    build:
      context: .
      dockerfile: Dockerfile-app
    depends_on:
      - phonebook-mysql
    ports:
      - "8181:8181"
    restart: always

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    restart: unless-stopped
    ports:
      - "8978:8978"
    volumes:
      - cloudbeaver-workspace:/opt/cloudbeaver/workspace
    depends_on:
      - phonebook-mysql

volumes:
  cloudbeaver-workspace: